### ISSUE TITLE
Improve contributing guidelines

### ISSUE THREAD

**Issue by choldgraf** [rheiland/xml2jupyter#5]
There are currently fairly minimal contributing guidelines in the README - they mention GitHub issues, but nothing really about how folks can get involved with the project and submit their own pull requests, and there aren't any guidelines helping people navigate the codebase itself (e.g. how it's structured, overview of scripts/modules/etc). For example, [here's a contributing file for one of our projects](https://github.com/jupyter/repo2docker/blob/master/CONTRIBUTING.md). You don't necessarily need *that* much information, but some more than just "use github issues" would be helpful.

**Comment by choldgraf** [comment]
(note, if you don't really want people to contribute development, that's fine too...it's just a bit unclear from the contributing guidelines)

**Comment by rheiland** [comment]
I tried to clarify and provide a bit more guidance in the "Contributions" section.

**Comment by choldgraf** [comment]
nice, thanks
